service: order-payment

plugins:
  - serverless-pseudo-parameters

custom:
  aws: ${file(./config.js):aws}

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.aws.tableNames.orderTable}

functions:
  createOrder:
    handler: handlers/orderHandler.create

resources:
  Resources:
    orderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.aws.tableNames.orderTable}
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: orderId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

